version: '3.8'

services:
  db:
    image: postgres:16
    container_name: shareit-db
    restart: always
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - shareit-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: shareit-app
    restart: on-failure
    ports:
      - "8088:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db
volumes:
  shareit-data: